
name: 'my_dbt_project'
version: '1.0.0'

profile: 'my_dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:        
  - "target"
  - "dbt_packages"

models:
  my_dbt_project:
    staging:
      +materialized: view      
      +schema: staging         
    marts:
      +materialized: table     
      +schema: marts           
    utils:
      +materialized: ephemeral 
