version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: enrollments
        description: "Сырые данные о записях пользователей на курсы"
        columns:
          - name: id
            description: "Уникальный идентификатор записи"
            tests:
              - not_null
              - unique
          - name: user_id
            description: "ID пользователя"
            tests:
              - not_null
          - name: course_id
            description: "ID курса"
            tests:
              - not_null
          - name: enrolled_at
            description: "Дата записи на курс"
            tests:
              - not_null

      - name: users
        description: "Сырые данные о пользователях"
        columns:
          - name: user_id
            description: "Уникальный идентификатор пользователя"
            tests:
              - not_null
              - unique
          - name: name
            description: "Имя пользователя"
          - name: age
            description: "Возраст пользователя"
          - name: email
            description: "Email адрес пользователя"
            tests:
              - not_null
          - name: registration_date
            description: "Дата регистрации пользователя"

      - name: courses
        description: "Сырые данные о курсах"
        columns:
          - name: course_id
            description: "Уникальный идентификатор курса"
            tests:
              - not_null
              - unique
          - name: title
            description: "Название курса"
            tests:
              - not_null
          - name: category
            description: "Категория курса"
          - name: created_at
            description: "Дата создания курса"

      - name: lesson_views
        description: "Сырые данные о просмотрах уроков пользователями"
        columns:
          - name: id
            description: "Уникальный идентификатор просмотра"
            tests:
              - not_null
              - unique
          - name: user_id
            description: "ID пользователя"
            tests:
              - not_null
          - name: lesson_id
            description: "ID урока"
            tests:
              - not_null
          - name: viewed_at
            description: "Дата и время просмотра урока"
            tests:
              - not_null
