version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: enrollments
        description: "Сырые данные о записях пользователей на курсы"
        columns:
          - name: id
            description: "Уникальный идентификатор записи"
            tests: [not_null, unique]
          - name: user_id
            description: "ID пользователя"
            tests: [not_null]
          - name: course_id
            description: "ID курса"
            tests: [not_null]
          - name: enrolled_at
            description: "Дата записи на курс"
            tests: [not_null]

      - name: users
        description: "Сырые данные о пользователях"
        columns:
          - name: user_id
            description: "Уникальный идентификатор пользователя"
            tests: [not_null, unique]
          - name: name
            description: "Имя пользователя"
          - name: age
            description: "Возраст пользователя"
          - name: email
            description: "Email адрес пользователя"
            tests: [not_null]
          - name: registration_date
            description: "Дата регистрации пользователя"

      - name: courses
        description: "Сырые данные о курсах"
        columns:
          - name: course_id
            description: "Уникальный идентификатор курса"
            tests: [not_null, unique]
          - name: title
            description: "Название курса"
            tests: [not_null]
          - name: category
            description: "Категория курса"
          - name: created_at
            description: "Дата создания курса"

      - name: lesson_views
        description: "Сырые данные о просмотрах уроков пользователями"
        columns:
          - name: id
            description: "Уникальный идентификатор просмотра"
            tests: [not_null, unique]
          - name: user_id
            description: "ID пользователя"
            tests: [not_null]
          - name: lesson_id
            description: "ID урока"
            tests: [not_null]
          - name: viewed_at
            description: "Дата и время просмотра урока"
            tests: [not_null]

      - name: lessons
        description: "Сырые данные об уроках"
        columns:
          - name: lesson_id
            description: "Уникальный идентификатор урока"
            tests: [not_null, unique]
          - name: course_id
            description: "ID курса, к которому относится урок"
            tests: [not_null]
          - name: title
            description: "Название урока"
            tests: [not_null]
          - name: duration_min
            description: "Длительность урока в минутах"
            tests: [not_null]

  - name: core
    schema: core
    tables:
      - name: dim_course
        description: "Измерение: курсы"
        columns:
          - name: course_id
            description: "ID курса"
            tests: [not_null, unique]
          - name: title
            description: "Название курса"
            tests: [not_null]
          - name: category
            description: "Категория курса"

      - name: dim_lesson
        description: "Измерение: уроки"
        columns:
          - name: lesson_id
            description: "ID урока"
            tests: [not_null, unique]
          - name: title
            description: "Название урока"
            tests: [not_null]
          - name: duration_min
            description: "Длительность урока в минутах"
            tests: [not_null]
          - name: course_id
            description: "ID курса"
            tests: [not_null]

      - name: dim_user
        description: "Измерение: пользователи"
        columns:
          - name: user_id
            description: "ID пользователя"
            tests: [not_null, unique]
          - name: name
            description: "Имя пользователя"
          - name: age
            description: "Возраст пользователя"
          - name: email
            description: "Email пользователя"
            tests: [not_null]
          - name: registration_date
            description: "Дата регистрации"

      - name: fact_enrollments
        description: "Факт: записи пользователей на курсы"
        columns:
          - name: user_id
            description: "ID пользователя"
            tests: [not_null]
          - name: course_id
            description: "ID курса"
            tests: [not_null]
          - name: enrolled_at
            description: "Дата записи на курс"
            tests: [not_null]

      - name: fact_lesson_views
        description: "Факт: просмотры уроков пользователями"
        columns:
          - name: user_id
            description: "ID пользователя"
            tests: [not_null]
          - name: lesson_id
            description: "ID урока"
            tests: [not_null]
          - name: course_id
            description: "ID курса"
            tests: [not_null]
          - name: viewed_at
            description: "Дата и время просмотра"
            tests: [not_null]
